### ISSUE TITLE
I linked this to my project and it doesn't seem to do anything.

### ISSUE THREAD

**Issue by cypressru** [8bitprodigy/mse#2]
As the title suggests, I have linked this project into one of my games but it doesn't seem to give me access to any frameworks, let alone a particularly ethical one.
I'm combing through the github to try to figure out what exactly I need to do to get this framework to work, but after many hours of debugging and parsing through this code,  I'm at a loss. I asked ChatGPT, Gemini, even Claude...

**Comment by dont-test-da-master** [comment]
I am also having problems. I submitted a PR which should help alleviate these issues. Let's hope!
